### ISSUE TITLE
Merging Customizations

### ISSUE THREAD

**Issue by forkmantis** [LeadPipeSoftware/medkit#2]
Let's say you have a base .vimrc, and an environment specific one:

```
.vimrc.symlink
.vimrc.macos.symlink
```

How should we go about combining them?  

My first idea is to have a dist folder that you build into.  In a case like this, the build may be as simple as concatenating the two files into one.  From there, you would just symlink to the built file, rather than to the source file(s).

**Comment by gregmajor** [comment]
Hmmm... that is a good question. Maybe we adopt a templating system like mustache. We'd just have to be sure to transform the _base_ file (ex: `.vimrc.symlink`) and remove the template(s) if there's no more specific file available (ex: `.vimrc.macos.symlink`).

**Comment by forkmantis** [comment]
I can think of a few scenarios.

1. a common file is defined, but no environment specific file is defined.  i.e. there is a .vimrc.symlink, but no .vimrc.{environment}.symlink file.  In that case, you just link the common file.

2. There is no common file, but there is an environment file that matches your environment.  i.e., your environment is macos and there is a .vimrc.macos.symlink file, so you symlink the environment specific file.

3. There is a common file and an environment specific file that matches your environment.  i.e., .vimrc.symlink and .vimrc.macos.symlink and your environment is macos.  In this case, you combine the two files and symlink to the result.

4. There is no common file, and no environment specific file that matches your environment.  i.e., your environment is macos, and only .vimrc.wsl.symlink exists.  Do not symlink anything.

**Comment by gregmajor** [comment]
I'm feeling like this is a post-MVP issue.

**Comment by forkmantis** [comment]
Based on our more recent discussions on the ideas of environments, contexts, and later on, bundles, I'm thinking this may be obsolete.  I'm going to mark it closed, and update the README with those other ideas.
