### ISSUE TITLE
What is the core mission?

### ISSUE THREAD

**Issue by gregmajor** [LeadPipeSoftware/medkit#4]
# Mission
Looking over my [original dotfiles](https://github.com/gregmajor/dotfiles) repo, it's hard to summarize the mission clearly. It's really a combination of:

* _"I want my dotfiles to be consistent everywhere I have a need for them"_
* _"I want my `*.rc` files to not be a hot mess even if I use bash, zsh, or whatever"_
* _"I want to stand up a new machine with the right tools"_

## Consistent Dotfiles
The basic problem is solved with a convention-based folder structure that can be checked into source control and a tiny bit of code that knows how to recursively search that folder and create a symlink anywhere it finds a file ending with `.symlink`.

`medkit update dotfiles`

Not there? Create it! Already there? Prompt! Dead simple at first. Very shortly after that works we need to become OS agnostic. Then we can explore the notion of "environments" or "context" or what-have-you.

## Clean `*.rc` Files
This is it's own religious war. However, I think `medkit` can have a convention-driven solution that offers an out-of-the-box opinion. In the end, however, there's not much to it. Hell, maybe there's really _nothing_ to it other than a template.

## Software Installation
The bits about installing software are, in reality, problems that we're unlikely to truly solve. There are a lot of solutions that tackle the problem in different ways like [Homebrew](https://brew.sh/), [Vagrant](https://www.vagrantup.com/), [Ninite](https://ninite.com/), and [Boxstarter](http://boxstarter.org/) to name a few. So, should `medkit` simply provide commands that are convention-driven to allow users to use whatever works for them? For example:

`medkit run installers`

Being merely a convention thing that boils down to, "Go look in this folder, recursively, and exec anything you find that ends with `.installer`".

## New Machines
Got a new machine? Great! You need to do All The Things. Something like:

`medkit init`

**Comment by forkmantis** [comment]
The Mission and Consistent Dotfiles and New Machine sections sound pretty good as-is, aside from net yet having a fully baked notion of environment or context.  Basically, this feels like a rough draft of the README.md.  

As far as software installation goes, I like the idea of using convention to allow for more tools than homebrew.  A user may want to use different installers or combinations of installers on different environments.  For MVP, I'd be content to use a Homebrew/Linuxbrew solution, and tackle the problem of having environment specific brewfiles.

**Comment by gregmajor** [comment]
I feel like we've moved successfully into README-driven development and that it covers this issue and more.
